# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-03 04:26
from __future__ import unicode_literals

import apps.actividades.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActividadDetalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(default='', max_length=20)),
                ('imagen', models.ImageField(blank=True, upload_to=apps.actividades.models.photo_path)),
            ],
        ),
    ]
