# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-03 18:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0002_actividaddetalle'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividaddetalle',
            name='actividad',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='actividades.Actividad'),
        ),
    ]
