# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-12 23:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0003_actividaddetalle_actividad'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='nombre',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='descripcion',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='actividaddetalle',
            name='actividad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actividades.Actividad'),
        ),
    ]
