# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-17 03:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fotos', '0004_auto_20180131_1209'),
        ('actividades', '0005_auto_20170621_0018'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividaddetalle',
            name='foto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fotos.Foto'),
        ),
    ]
