# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-17 03:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0006_actividaddetalle_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividaddetalle',
            name='img_url',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
