# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-08-26 23:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0007_actividaddetalle_img_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='descripcion',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='nombre',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='actividaddetalle',
            name='descripcion',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
