# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-08-27 00:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0008_auto_20180826_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividaddetalle',
            name='descripcion',
            field=models.CharField(blank=True, default='', max_length=999),
        ),
    ]
