# Generated by Django 2.0 on 2017-05-22 20:01

import apps.perfil.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, upload_to=apps.perfil.models.user_directory_path),
        ),
    ]
