# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-16 00:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DescripcionFoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(default='', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_archivo', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='descripcionfoto',
            name='foto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fotos.Foto'),
        ),
    ]
