# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-16 01:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fotos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descripcionfoto',
            name='descripcion',
            field=models.TextField(default='', max_length=1000),
        ),
    ]
