# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-31 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fotos', '0003_descripcionfoto_vector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foto',
            name='nombre_archivo',
            field=models.TextField(),
        ),
    ]
