# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-27 02:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fotos', '0004_auto_20180131_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descripcionfoto',
            name='foto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='fotos.Foto'),
        ),
    ]
