# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-09-10 23:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fotos', '0006_auto_20180827_0008'),
    ]

    operations = [
        migrations.AddField(
            model_name='descripcionfoto',
            name='sinonimos',
            field=models.TextField(default='', max_length=999),
        ),
    ]
