# Generated by Django 2.0.dev20170510204018 on 2017-05-28 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(default='', max_length=20)),
                ('apellidos', models.CharField(default='', max_length=20)),
                ('fecha_nacimiento', models.DateField()),
            ],
        ),
    ]
