# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-03 01:45
from __future__ import unicode_literals

from django.db import migrations, models

import datetime


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='estado',
            field=models.CharField(choices=[(b'm', b'Masculino'), (b'f', b'Femenino'), (b'', b'')], default=b'', max_length=8, verbose_name=b'Estado'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name=b'fecha_nacimiento',
            field=models.DateField(default=datetime.date(2017, 9, 15)),
        ),
    ]
