# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-03 01:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0002_auto_20170603_0145'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paciente',
            old_name='estado',
            new_name='sexo',
        ),
    ]
