# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-03 02:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0003_auto_20170603_0146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='sexo',
            field=models.CharField(choices=[(b'', b''), (b'm', b'Masculino'), (b'f', b'Femenino')], default=b'', max_length=8, verbose_name=b'Sexo'),
        ),
    ]
