# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-16 00:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0004_auto_20170603_0209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='fecha_nacimiento',
            field=models.DateField(default=datetime.date(2017, 9, 16)),
        ),
    ]
