# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-28 17:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0006_auto_20170918_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name=b'fecha_nacimiento',
            field=models.DateField(default=datetime.date(2018, 1, 28)),
        ),
    ]
