# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-31 12:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0007_auto_20180128_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='fecha_nacimiento',
            field=models.DateField(default=datetime.date(2018, 1, 31)),
        ),
    ]
